kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-rest-world
  labels:
    app: hello-rest-world

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-rest-world
  template:
    metadata:
      labels:
        app: hello-rest-world
    spec:
      containers:
        - name: hello-rest-world
          image: traefik/whoami:v1.9.0
          ports:
            - containerPort: 80